/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Automatizar;
import apoio.ComboItem;
import apoio.CombosDAO;
import apoio.Formatacao;
import dao.CidadeDAO;
import dao.ClienteDAO;
import entidade.Cliente;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author artur
 */
public class IfrCliente extends javax.swing.JInternalFrame {

    private ArrayList<Cliente> clientes = new ArrayList<>();
    private Cliente clienteSelecionado = null;

    /**
     * Creates new form IfrCliente
     */
    public IfrCliente() {
        initComponents();

        Formatacao.formatarCpf(tffCPF);
        Formatacao.formatarData(tffNascimento);
        Formatacao.formatarTelefone(tffTelefone);

        new CombosDAO().popularComboBox("cidade", cbbCidade);
        popularTabela();

        alterarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TbpPrincipal = new javax.swing.JTabbedPane();
        PnlClienteLista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblClientes = new javax.swing.JTable();
        TxtFiltroNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtnLimparFiltro = new javax.swing.JButton();
        PnlClienteManutencao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        tffCPF = new javax.swing.JFormattedTextField();
        tffTelefone = new javax.swing.JFormattedTextField();
        tfdEmail = new javax.swing.JTextField();
        tfdLogradouro = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cbbCidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tffNascimento = new javax.swing.JFormattedTextField();
        BtnSalvar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnAtualizar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setTitle("Cadastro: Clientes");
        setPreferredSize(new java.awt.Dimension(960, 375));

        TbpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbpPrincipalMouseClicked(evt);
            }
        });

        TblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblClientes);
        if (TblClientes.getColumnModel().getColumnCount() > 0) {
            TblClientes.getColumnModel().getColumn(0).setMinWidth(150);
            TblClientes.getColumnModel().getColumn(0).setPreferredWidth(200);
        }

        jLabel9.setText("Filtro por nome:");

        BtnLimparFiltro.setText("Limpar");
        BtnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlClienteListaLayout = new javax.swing.GroupLayout(PnlClienteLista);
        PnlClienteLista.setLayout(PnlClienteListaLayout);
        PnlClienteListaLayout.setHorizontalGroup(
            PnlClienteListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlClienteListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlClienteListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(PnlClienteListaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimparFiltro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlClienteListaLayout.setVerticalGroup(
            PnlClienteListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlClienteListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlClienteListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(BtnLimparFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TbpPrincipal.addTab("Listagem", PnlClienteLista);

        jLabel2.setText("Nome:");

        jLabel3.setText("e-mail:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("CPF:");

        jLabel6.setText("Logradouro:");

        jLabel7.setText("Cidade:");

        tfdNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdNomeFocusLost(evt);
            }
        });

        tffCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCPFFocusLost(evt);
            }
        });

        tffTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tffTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneFocusLost(evt);
            }
        });

        tfdEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEmailFocusLost(evt);
            }
        });

        tfdLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdLogradouroFocusLost(evt);
            }
        });

        cbbCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbbCidadeFocusLost(evt);
            }
        });

        jLabel1.setText("Nascimento:");

        tffNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tffNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffNascimentoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout PnlClienteManutencaoLayout = new javax.swing.GroupLayout(PnlClienteManutencao);
        PnlClienteManutencao.setLayout(PnlClienteManutencaoLayout);
        PnlClienteManutencaoLayout.setHorizontalGroup(
            PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                            .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel7))
                            .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnlClienteManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfdLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfdNome, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                                .addComponent(tfdEmail)
                                .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                                    .addComponent(tffCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tffNascimento)))
                            .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlClienteManutencaoLayout.setVerticalGroup(
            PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlClienteManutencaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tffCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tffNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnlClienteManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfdLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TbpPrincipal.addTab("Manutenção", PnlClienteManutencao);

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnAtualizar.setText("Atualizar");
        BtnAtualizar.setEnabled(false);
        BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TbpPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSalvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnCancelar)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnAtualizar)
                    .addComponent(BtnExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        String msg = "Confirmar cadastro?";
        if (clienteSelecionado != null) {
            msg = "Confirmar alteração?";
        }

        if (JOptionPane.showConfirmDialog(this, msg, "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (verificarCampos()) {
                JOptionPane.showMessageDialog(this, "Há campo(s) com erro de preenchimento");
            } else {
                salvar();
            }
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void TbpPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbpPrincipalMouseClicked
        alterarBotoes();

        if (TbpPrincipal.getSelectedIndex() == 0) {
            limparRegistro();
            clienteSelecionado = null;
        } else {
            alterarBotoesUpdate(false);
        }
    }//GEN-LAST:event_TbpPrincipalMouseClicked

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        popularTabela();
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparFiltroActionPerformed
        TxtFiltroNome.setText("");
        popularTabela();
    }//GEN-LAST:event_BtnLimparFiltroActionPerformed

    private void TblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblClientesMouseClicked
        alterarBotoesUpdate(TblClientes.getSelectedRow() > -1);
    }//GEN-LAST:event_TblClientesMouseClicked

    private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarActionPerformed
        clienteSelecionado = new ClienteDAO().consultarId(clientes.get(TblClientes.getSelectedRow()).getId());

        preencherRegistro();

        TbpPrincipal.setSelectedIndex(1);

        alterarBotoesUpdate(false);
        alterarBotoes();
    }//GEN-LAST:event_BtnAtualizarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Confirmar exclusão do cliente?", "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (new ClienteDAO().excluir(clientes.get(TblClientes.getSelectedRow()).getId()) == null) {
                JOptionPane.showMessageDialog(this, "Cliente Excluido com sucesso!");
                popularTabela();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir Cliente");
            }
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void tffCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCPFFocusLost
        Automatizar.cpf(tffCPF, false);
    }//GEN-LAST:event_tffCPFFocusLost

    private void tffNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffNascimentoFocusLost
        Automatizar.data(tffNascimento, false);
    }//GEN-LAST:event_tffNascimentoFocusLost

    private void tfdEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEmailFocusLost
        Automatizar.email(tfdEmail, true);
    }//GEN-LAST:event_tfdEmailFocusLost

    private void tfdNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdNomeFocusLost
        Automatizar.nome(tfdNome, false);
    }//GEN-LAST:event_tfdNomeFocusLost

    private void tfdLogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdLogradouroFocusLost
        Automatizar.logradouro(tfdLogradouro, false);
    }//GEN-LAST:event_tfdLogradouroFocusLost

    private void tffTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneFocusLost
        Automatizar.telefone(tffTelefone, false);
    }//GEN-LAST:event_tffTelefoneFocusLost

    private void cbbCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbCidadeFocusLost
        Automatizar.comboBox(cbbCidade, false);
    }//GEN-LAST:event_cbbCidadeFocusLost

    private void salvar() {
        Cliente cliente = criarCliente();

        ClienteDAO clienteDAO = new ClienteDAO();
        if (clienteSelecionado == null) {
            if (clienteDAO.salvar(cliente) == null) {
                limparRegistro();
                popularTabela();
                JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao acadastrar Cliente.");
            }
        } else {
            if (clienteDAO.atualizar(cliente) == null) {
                limparRegistro();
                popularTabela();
                JOptionPane.showMessageDialog(this, "Cliente alterado com sucesso!");
                clienteSelecionado = null;
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar Cliente.");
            }
        }
    }

    private Cliente criarCliente() {
        String nome = tfdNome.getText();
        String email = tfdEmail.getText();
        String cpf = tffCPF.getText();
        String telefone = tffTelefone.getText();
        String logradouro = tfdLogradouro.getText();
        ComboItem item = (ComboItem) cbbCidade.getSelectedItem();
        int idCidade = item.getId();
        LocalDate nascimento = new Formatacao().stringToLocalDate(tffNascimento.getText());

        if (clienteSelecionado == null) {
            return new Cliente(nome, email, cpf, telefone, logradouro, idCidade, nascimento);

        } else {
            return new Cliente(clienteSelecionado.getId(), nome, email, cpf, telefone, logradouro, idCidade, nascimento);
        }
    }

    private void limparRegistro() {
        tfdNome.setText("");
        tfdEmail.setText("");
        tffCPF.setText("");
        tffTelefone.setText("");
        tfdLogradouro.setText("");
        cbbCidade.setSelectedIndex(0);
        tffNascimento.setText("");

        tfdNome.requestFocus();

        tffNascimento.setBackground(Formatacao.colorNeutral());
        tffNascimento.setBackground(Formatacao.colorNeutral());
        tffNascimento.setBackground(Formatacao.colorNeutral());
        tffNascimento.setBackground(Formatacao.colorNeutral());
        tffNascimento.setBackground(Formatacao.colorNeutral());
        cbbCidade.setBorder(BorderFactory.createLineBorder(Formatacao.colorNeutral(), 0));
        tffNascimento.setBackground(Formatacao.colorNeutral());
    }

    private void preencherRegistro() {
        tfdNome.setText(clienteSelecionado.getNome());
        tfdEmail.setText(clienteSelecionado.getEmail());
        tffCPF.setText(clienteSelecionado.getCpf());
        tffTelefone.setText(clienteSelecionado.getTelefone());
        tfdLogradouro.setText(clienteSelecionado.getLogradouro());
        tffNascimento.setText(new Formatacao().localDateToString(clienteSelecionado.getNascimento()));

        new CombosDAO().definirItemCombo(cbbCidade, clienteSelecionado.getCidade());

        tfdNome.requestFocus();
    }

    private void alterarBotoes() {
        BtnBuscar.setEnabled(TbpPrincipal.getSelectedIndex() == 0);
        BtnSalvar.setEnabled(TbpPrincipal.getSelectedIndex() == 1);
    }

    private void popularTabela() {
        alterarBotoesUpdate(false);
        popularArrayClientes();

        Object[] cabecalho = {"Nome", "Telefone", "Nascimento", "Cidade", "Logradouro", "e-mail"};

        DefaultTableModel model = new DefaultTableModel(cabecalho, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        CidadeDAO cidadeDAO = new CidadeDAO();

        for (Cliente cliente : clientes) {
            String nome = cliente.getNome();
            String telefone = cliente.getTelefone();
            String cidade = cidadeDAO.consultarId(cliente.getCidade()).getNome();
            String logradouro = cliente.getLogradouro();
            String email = cliente.getEmail();

            String nascimento = new Formatacao().localDateToString(cliente.getNascimento());

            String[] row = {nome, telefone, nascimento, cidade, logradouro, email};

            model.addRow(row);
        }

        TblClientes.setModel(model);
        TblClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        TableColumn coluna = null;

        for (int i = 0; i < TblClientes.getColumnCount(); i++) {
            coluna = TblClientes.getColumnModel().getColumn(i);
            coluna.setResizable(false);

            switch (i) {
                case 0: //Nome
                    coluna.setMaxWidth(400);
                    break;
                case 1: //Telefone
                    coluna.setMaxWidth(150);
                    break;
                case 2: //Nascimento
                    coluna.setMaxWidth(80);
                    break;
                case 3: //Cidade
                    coluna.setMaxWidth(200);
                    break;
                case 4: //Logradouro
                    coluna.setMaxWidth(300);
                    break;
                case 5: //e-mail
                    coluna.setMaxWidth(200);
                    break;
            }
        }
    }

    private void popularArrayClientes() {
        ClienteDAO clienteDAO = new ClienteDAO();

        if (TxtFiltroNome.getText().length() > 0) {
            String DML = "SELECT * FROM cliente "
                    + "WHERE nome ILIKE '%" + TxtFiltroNome.getText() + "%'"
                    + "ORDER BY nome;";

            clientes = clienteDAO.consultar(DML);
        } else {
            clientes = clienteDAO.consultarTodos();
        }

    }

    private void alterarBotoesUpdate(boolean setTo) {
        BtnAtualizar.setEnabled(setTo);
        BtnExcluir.setEnabled(setTo);
    }

    private boolean verificarCampos() {
        Automatizar.cpf(tffCPF, false);
        Automatizar.data(tffNascimento, false);
        Automatizar.email(tfdEmail, true);
        Automatizar.nome(tfdNome, false);
        Automatizar.logradouro(tfdLogradouro, false);
        Automatizar.telefone(tffTelefone, false);
        Automatizar.comboBox(cbbCidade, false);

        if (Automatizar.cpf(tffCPF, false)
                || Automatizar.data(tffNascimento, false)
                || Automatizar.email(tfdEmail, true)
                || Automatizar.nome(tfdNome, false)
                || Automatizar.logradouro(tfdLogradouro, false)
                || Automatizar.telefone(tffTelefone, false)
                || Automatizar.comboBox(cbbCidade, false)) {
            return true;
        } else {
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnLimparFiltro;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JPanel PnlClienteLista;
    private javax.swing.JPanel PnlClienteManutencao;
    private javax.swing.JTable TblClientes;
    private javax.swing.JTabbedPane TbpPrincipal;
    private javax.swing.JTextField TxtFiltroNome;
    private javax.swing.JComboBox<String> cbbCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdLogradouro;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tffCPF;
    private javax.swing.JFormattedTextField tffNascimento;
    private javax.swing.JFormattedTextField tffTelefone;
    // End of variables declaration//GEN-END:variables
}
