/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.Automatizar;
import apoio.Formatacao;
import apoio.Validacao;
import dao.FornecedorDAO;
import entidade.Fornecedor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author artur
 */
public class IfrFornecedor extends javax.swing.JInternalFrame {
    
    final String titulo = "Fornecedor";

    ArrayList<Fornecedor> fornecedores;
    Fornecedor fornecedorSelecionado = null;

    /**
     * Creates new form IfrFornecedor
     */
    public IfrFornecedor() {
        initComponents();

        Formatacao.formatarCnpj(tffCnpj);
        Formatacao.formatarTelefone(tffTelefone);

        alterarBotoes();
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TbpPrincipal = new javax.swing.JTabbedPane();
        PnlFornecedorLista = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TxtFiltroNome = new javax.swing.JTextField();
        BtnLimparFiltro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblListagem = new javax.swing.JTable();
        PnlFornecedorManutencao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        tfdEmail = new javax.swing.JTextField();
        tffTelefone = new javax.swing.JFormattedTextField();
        tffCnpj = new javax.swing.JFormattedTextField();
        BtnBuscar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        BtnAtualizar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setTitle("Cadastro: Fornecedores");

        TbpPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbpPrincipalMouseClicked(evt);
            }
        });

        jLabel5.setText("Filtro por nome:");

        BtnLimparFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom.png"))); // NOI18N
        BtnLimparFiltro.setText("Limpar");
        BtnLimparFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparFiltroActionPerformed(evt);
            }
        });

        TblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblListagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblListagemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TblListagem);

        javax.swing.GroupLayout PnlFornecedorListaLayout = new javax.swing.GroupLayout(PnlFornecedorLista);
        PnlFornecedorLista.setLayout(PnlFornecedorListaLayout);
        PnlFornecedorListaLayout.setHorizontalGroup(
            PnlFornecedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFornecedorListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFornecedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(PnlFornecedorListaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLimparFiltro)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnlFornecedorListaLayout.setVerticalGroup(
            PnlFornecedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFornecedorListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFornecedorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtFiltroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLimparFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        TbpPrincipal.addTab("Listagem", PnlFornecedorLista);

        jLabel1.setText("Nome:");

        jLabel2.setText("e-mail:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("CNPJ:");

        tfdNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdNomeFocusLost(evt);
            }
        });

        tfdEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEmailFocusLost(evt);
            }
        });

        tffTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tffTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffTelefoneFocusLost(evt);
            }
        });

        tffCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tffCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffCnpjFocusLost(evt);
            }
        });

        javax.swing.GroupLayout PnlFornecedorManutencaoLayout = new javax.swing.GroupLayout(PnlFornecedorManutencao);
        PnlFornecedorManutencao.setLayout(PnlFornecedorManutencaoLayout);
        PnlFornecedorManutencaoLayout.setHorizontalGroup(
            PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFornecedorManutencaoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlFornecedorManutencaoLayout.createSequentialGroup()
                        .addComponent(tffCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        PnlFornecedorManutencaoLayout.setVerticalGroup(
            PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlFornecedorManutencaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlFornecedorManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        TbpPrincipal.addTab("Manutenção", PnlFornecedorManutencao);

        BtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trash-bin.png"))); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.setEnabled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        BtnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        BtnAtualizar.setText("Editar");
        BtnAtualizar.setEnabled(false);
        BtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtualizarActionPerformed(evt);
            }
        });

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add-file.png"))); // NOI18N
        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cross.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(BtnExcluir)
                    .addComponent(BtnAtualizar)
                    .addComponent(BtnSalvar)
                    .addComponent(BtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        String msg = Formatacao.mensagemConfirmacaoSalvar(this.titulo);
        if (fornecedorSelecionado != null) {
            msg = Formatacao.mensagemConfirmacaoAtualizar(this.titulo);
        }

        if (JOptionPane.showConfirmDialog(this, msg, "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (verificarCampos()) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemErroPreenchimento());
            } else {
                salvar();
            }
        }
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        popularTabela();
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void TbpPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbpPrincipalMouseClicked
        alterarBotoes();
        if (TbpPrincipal.getSelectedIndex() == 0) {
            limparRegistro();
            fornecedorSelecionado = null;
        } else {
            TxtFiltroNome.setText("");
        }
    }//GEN-LAST:event_TbpPrincipalMouseClicked

    private void BtnLimparFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparFiltroActionPerformed
        TxtFiltroNome.setText("");

        popularTabela();
    }//GEN-LAST:event_BtnLimparFiltroActionPerformed

    private void tffCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffCnpjFocusLost
        Automatizar.cnpj(tffCnpj, false);
    }//GEN-LAST:event_tffCnpjFocusLost

    private void tfdEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEmailFocusLost
        Automatizar.email(tfdEmail, true);
    }//GEN-LAST:event_tfdEmailFocusLost

    private void BtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtualizarActionPerformed
        fornecedorSelecionado = fornecedores.get(TblListagem.getSelectedRow());

        tfdNome.setText(fornecedorSelecionado.getNome());
        tffCnpj.setText(fornecedorSelecionado.getCnpj());
        tffTelefone.setText(fornecedorSelecionado.getTelefone());
        tfdEmail.setText(fornecedorSelecionado.getEmail());

        TbpPrincipal.setSelectedIndex(1);

        tfdNome.requestFocus();

        ativarBotoesEdicao(false);
        alterarBotoes();
    }//GEN-LAST:event_BtnAtualizarActionPerformed

    private void TblListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblListagemMouseClicked
        if (TblListagem.getSelectedRow() > -1) {
            ativarBotoesEdicao(true);
        }
    }//GEN-LAST:event_TblListagemMouseClicked

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this, Formatacao.mensagemConfirmacaoExclusao(this.titulo), "Confirmação", JOptionPane.YES_NO_OPTION) == 0) {
            if (new FornecedorDAO().excluir(fornecedores.get(TblListagem.getSelectedRow()).getId()) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemExclusaoSucess(this.titulo));
                popularTabela();
                ativarBotoesEdicao(false);
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemExclusaoError(this.titulo));
            }
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void tfdNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdNomeFocusLost
        Automatizar.nome(tfdNome, false);
    }//GEN-LAST:event_tfdNomeFocusLost

    private void tffTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffTelefoneFocusLost
        Automatizar.telefone(tffTelefone, false);
    }//GEN-LAST:event_tffTelefoneFocusLost

    private Fornecedor criarFornecedor() {
        String nome = tfdNome.getText();
        String email = tfdEmail.getText();
        String telefone = tffTelefone.getText();
        String cnpj = tffCnpj.getText();

        if (fornecedorSelecionado == null) {
            return new Fornecedor(nome, email, telefone, cnpj);
        } else {
            return new Fornecedor(fornecedorSelecionado.getId(), nome, email, telefone, cnpj);
        }
    }

    private void limparRegistro() {
        tfdNome.setText("");
        tfdEmail.setText("");
        tffTelefone.setText("");
        tffCnpj.setText("");

        tfdNome.requestFocus();

        tffCnpj.setBackground(Formatacao.colorNeutral());
        tffCnpj.setBackground(Formatacao.colorNeutral());
        tffCnpj.setBackground(Formatacao.colorNeutral());
        tffCnpj.setBackground(Formatacao.colorNeutral());
    }

    private void salvar() {
        Fornecedor fornecedor = criarFornecedor();

        if (fornecedorSelecionado == null) {
            if (new FornecedorDAO().salvar(fornecedor) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemSalvarSucess(this.titulo));
                limparRegistro();
                popularTabela();
                TbpPrincipal.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemSalvarError(this.titulo));
            }
        } else {
            if (new FornecedorDAO().atualizar(fornecedor) == null) {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarSucess(this.titulo));
                limparRegistro();
                fornecedorSelecionado = null;
                popularTabela();
                TbpPrincipal.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, Formatacao.mensagemAtualizarError(this.titulo));
            }
        }
    }

    private void popularTabela() {
        popularArrayFornecedores();

        Object[] cabecalho = {
            "Nome",
            "CNPJ",
            "Telefone",
            "e-mail"
        };

        DefaultTableModel model = new DefaultTableModel(cabecalho, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Fornecedor fornecedor : fornecedores) {
            String nome = fornecedor.getNome();
            String cnpj = fornecedor.getCnpj();
            String telefone = fornecedor.getTelefone();
            String email = fornecedor.getEmail();

            String[] row = {
                nome,
                cnpj,
                telefone,
                email
            };

            model.addRow(row);
        }

        TblListagem.setModel(model);
        TblListagem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        TableColumn coluna = null;
        for (int i = 0; i < TblListagem.getColumnCount(); i++) {
            coluna = TblListagem.getColumnModel().getColumn(i);
            coluna.setResizable(false);

            switch (i) {
                case 0:
                    coluna.setMaxWidth(650);
                    break;
                case 1:
                    coluna.setMaxWidth(300);
                    break;
                case 2:
                    coluna.setMaxWidth(250);
                    break;
                case 3:
                    coluna.setMaxWidth(600);
                    break;
            }
        }
    }

    private void popularArrayFornecedores() {
        FornecedorDAO fornecedorDAO = new FornecedorDAO();

        if (TxtFiltroNome.getText().length() > 0) {
            String DML = "SELECT * FROM fornecedor "
                    + "WHERE nome ILIKE '%" + TxtFiltroNome.getText() + "%' "
                    + "ORDER BY nome;";

            fornecedores = fornecedorDAO.consultar(DML);
        } else {
            fornecedores = fornecedorDAO.consultarTodos();
        }
    }

    private void alterarBotoes() {
        BtnBuscar.setEnabled(TbpPrincipal.getSelectedIndex() == 0);
        BtnSalvar.setEnabled(TbpPrincipal.getSelectedIndex() == 1);
    }

    private void ativarBotoesEdicao(boolean setTo) {
        BtnExcluir.setEnabled(setTo);
        BtnAtualizar.setEnabled(setTo);
    }

    private boolean verificarCampos() {
        Automatizar.nome(tfdNome, false);
        Automatizar.cnpj(tffCnpj, false);
        Automatizar.telefone(tffTelefone, false);
        Automatizar.email(tfdEmail, true);

        return (Automatizar.nome(tfdNome, false)
                || Automatizar.cnpj(tffCnpj, false)
                || Automatizar.telefone(tffTelefone, false)
                || Automatizar.email(tfdEmail, true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtualizar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnLimparFiltro;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JPanel PnlFornecedorLista;
    private javax.swing.JPanel PnlFornecedorManutencao;
    private javax.swing.JTable TblListagem;
    private javax.swing.JTabbedPane TbpPrincipal;
    private javax.swing.JTextField TxtFiltroNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tffCnpj;
    private javax.swing.JFormattedTextField tffTelefone;
    // End of variables declaration//GEN-END:variables
}
